FROM debian:buster

RUN apt-get update \
    && apt-get -y install curl less zip unzip groff openssh-client git

# Install Terraform on the image
RUN curl "https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip" -o "terraform.zip" \
    && unzip "terraform.zip" \
    && cp ./terraform /usr/bin

# Install the AWS CLI on the image
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip "awscliv2.zip" \
    && ./aws/install 